name: Build
on:
  push:
    branches:
      - master
      - main
env:
  REGION: us-central1
  MEMORY: 512M
  GCP_APPLICATION: app-2

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
      
    - name: Build & Publish
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud builds submit --config cloudbuild.yaml --substitutions=_ENV_VAR_1="1",_ENV_VAR_2="2",_WORKERS="2" .
        gcloud config set run/region $REGION
      
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud components install beta && \
        gcloud beta run deploy $GCP_APPLICATION --image gcr.io/YOUR_TAG \
        --platform managed \
        --allow-unauthenticated \
        --memory $MEMORY && \
        gcloud run services add-iam-policy-binding $GCP_APPLICATION --member="allUsers" --role="roles/run.invoker"
