FROM python:3.10.1-slim-buster

COPY ./src/requirements.txt /api/requirements.txt

WORKDIR /api

RUN apt-get update \
&& apt-get install -y --no-install-recommends git \
&& apt-get purge -y --auto-remove \
&& rm -rf /var/lib/apt/lists/*

RUN pip install -r requirements.txt --no-cache-dir

COPY ./src /api/src
COPY ./test /api/test

ENV PYTHONPATH=$(pwd)
ENV PYTHONUNBUFFERED=1

EXPOSE 5000

RUN mkdir -p /api/src/logs
RUN chmod 777 -R /api/src/

VOLUME /api/src
VOLUME /api/test

ENTRYPOINT python -u src/main.py
